### ISSUE TITLE
Validation error when applying a coupon

### ISSUE THREAD

**Issue by Reached** [happypixels/laravel-shopr#13]
**Describe the bug**

When trying to add a coupon code a 422 validation error is thrown. 

**To Reproduce**
1. Make sure your database contains a valid coupon
2. Make an ajax post request to the "/api/shopr/cart/discounts" endpoint with a body of a code `{code: 'somecode'}`
3. See 422 validation error in the console

**Might help**
My assumption is that the rules array is colliding with the custom rules array set in the configuration file, because I tried to override the original rules array in CartDiscountController.php `$rules = ['required', 'string'];` with my own implementation it worked: 

```
$request->validate([
            'code' => 'required|string'
        ]);
```

instead of 

```
$rules = ['required', 'string'];
```

But obviously this is not compatible with the custom rules 🤔

**Comment by mattias-sanfridsson** [comment]
@Reached Interesting! What was the exact validation error you received? I'll look into it!

**Comment by Reached** [comment]
My bad, I simply think that I made a mistake somewhere! It appears to be working correctly now 🤔 
Sorry if I wasted your time!
