### ISSUE TITLE
Include the discounted amount on the $order

### ISSUE THREAD

**Issue by Reached** [happypixels/laravel-shopr#16]
I think for many shop-owners it would be really valuable to know if/when a discount has been given on an order, currently this info is not included in the $order object that is created in `convertToOrder`. 

**Describe the solution you'd like**
Perhaps a nullable column "discounted_amount" on the `orders` table or a direct relation between the discounts and the order table (however I'm not sure about this approach).

This is a minor thing obviously :) what do you think though?

**Comment by mattias-sanfridsson** [comment]
Might be valuable, yes! But can you not solve this by iterating the order items? Each shoppable has a `isDiscount()`-method which returns true for discount coupons. So something like this should be possible: 
```
foreach($order->items as $item){
    if($item->shoppable->isDiscount()){
        // It's a discount.
    }
}
```
Not the prettiest, but maybe sufficient for your case?

**Comment by Reached** [comment]
Oh, yea that would definitely suffice for now, thanks! 👍

**Comment by mattias-sanfridsson** [comment]
Sweet! Let me know if you have the need for this again, I can def see the value in your suggestion 👍 I’ll try and document the internals a little better as well to make this kind of thing easier.
