### ISSUE TITLE
Call to undefined method Illuminate\Events\Dispatcher::fire()

### ISSUE THREAD

**Issue by jenky** [happypixels/laravel-shopr#33]
**Describe the bug**
`Call to undefined method Illuminate\Events\Dispatcher::fire()`

**To Reproduce**
Add a item to cart using Laravel 5.8

**Additional context**
The `fire` method of the `Illuminate\Events\Dispatcher` class has been removed in Laravel 5.8. The document page recommend using `dispatch` instead.

![Screen Shot 2019-08-09 at 18 51 34](https://user-images.githubusercontent.com/1808758/62777226-0ff59b00-bad7-11e9-8020-2f4f57d5bc0e.png)

**Comment by mattias-sanfridsson** [comment]
Thanks! I'll take a look at this ASAP.

**Comment by mattias-sanfridsson** [comment]
@jenky Should be fixed in v1.3.1.
